<?php

return array(
    array('id' => '1','site' => '1','pid' => '0','pids' => '0','name' => '北京','cname' => 'beijing','child' => '0','hidden' => '0','childids' => '1','displayorder' => '0'),
    array('id' => '2','site' => '1','pid' => '0','pids' => '0','name' => '天津','cname' => 'tianjin','child' => '0','hidden' => '0','childids' => '2','displayorder' => '0'),
    array('id' => '3','site' => '1','pid' => '0','pids' => '0','name' => '上海','cname' => 'shanghai','child' => '0','hidden' => '0','childids' => '3','displayorder' => '0'),
    array('id' => '4','site' => '1','pid' => '0','pids' => '0','name' => '重庆','cname' => 'chongqing','child' => '0','hidden' => '0','childids' => '4','displayorder' => '0'),
    array('id' => '5','site' => '1','pid' => '0','pids' => '0','name' => '黑龙江','cname' => 'heilongjiang','child' => '0','hidden' => '0','childids' => '5','displayorder' => '0'),
    array('id' => '6','site' => '1','pid' => '0','pids' => '0','name' => '吉林','cname' => 'jilin','child' => '0','hidden' => '0','childids' => '6','displayorder' => '0'),
    array('id' => '7','site' => '1','pid' => '0','pids' => '0','name' => '辽宁','cname' => 'liaoning','child' => '0','hidden' => '0','childids' => '7','displayorder' => '0'),
    array('id' => '8','site' => '1','pid' => '0','pids' => '0','name' => '河北','cname' => 'hebei','child' => '0','hidden' => '0','childids' => '8','displayorder' => '0'),
    array('id' => '9','site' => '1','pid' => '0','pids' => '0','name' => '河南','cname' => 'henan','child' => '0','hidden' => '0','childids' => '9','displayorder' => '0'),
    array('id' => '10','site' => '1','pid' => '0','pids' => '0','name' => '山东','cname' => 'shandong','child' => '0','hidden' => '0','childids' => '10','displayorder' => '0'),
    array('id' => '11','site' => '1','pid' => '0','pids' => '0','name' => '江苏','cname' => 'jiangsu','child' => '0','hidden' => '0','childids' => '11','displayorder' => '0'),
    array('id' => '12','site' => '1','pid' => '0','pids' => '0','name' => '山西','cname' => 'shanxi','child' => '0','hidden' => '0','childids' => '12','displayorder' => '0'),
    array('id' => '13','site' => '1','pid' => '0','pids' => '0','name' => '陕西','cname' => 'shanxi1','child' => '0','hidden' => '0','childids' => '13','displayorder' => '0'),
    array('id' => '14','site' => '1','pid' => '0','pids' => '0','name' => '甘肃','cname' => 'gansu','child' => '0','hidden' => '0','childids' => '14','displayorder' => '0'),
    array('id' => '15','site' => '1','pid' => '0','pids' => '0','name' => '四川','cname' => 'sichuan','child' => '0','hidden' => '0','childids' => '15','displayorder' => '0'),
    array('id' => '16','site' => '1','pid' => '0','pids' => '0','name' => '青海','cname' => 'qinghai','child' => '0','hidden' => '0','childids' => '16','displayorder' => '0'),
    array('id' => '17','site' => '1','pid' => '0','pids' => '0','name' => '湖南','cname' => 'hunan','child' => '0','hidden' => '0','childids' => '17','displayorder' => '0'),
    array('id' => '18','site' => '1','pid' => '0','pids' => '0','name' => '湖北','cname' => 'hubei','child' => '0','hidden' => '0','childids' => '18','displayorder' => '0'),
    array('id' => '19','site' => '1','pid' => '0','pids' => '0','name' => '江西','cname' => 'jiangxi','child' => '0','hidden' => '0','childids' => '19','displayorder' => '0'),
    array('id' => '20','site' => '1','pid' => '0','pids' => '0','name' => '安徽','cname' => 'anhui','child' => '0','hidden' => '0','childids' => '20','displayorder' => '0'),
    array('id' => '21','site' => '1','pid' => '0','pids' => '0','name' => '浙江','cname' => 'zhejiang','child' => '0','hidden' => '0','childids' => '21','displayorder' => '0'),
    array('id' => '22','site' => '1','pid' => '0','pids' => '0','name' => '福建','cname' => 'fujian','child' => '0','hidden' => '0','childids' => '22','displayorder' => '0'),
    array('id' => '23','site' => '1','pid' => '0','pids' => '0','name' => '广东','cname' => 'guangdong','child' => '0','hidden' => '0','childids' => '23','displayorder' => '0'),
    array('id' => '24','site' => '1','pid' => '0','pids' => '0','name' => '广西','cname' => 'guangxi','child' => '0','hidden' => '0','childids' => '24','displayorder' => '0'),
    array('id' => '25','site' => '1','pid' => '0','pids' => '0','name' => '贵州','cname' => 'guizhou','child' => '0','hidden' => '0','childids' => '25','displayorder' => '0'),
    array('id' => '26','site' => '1','pid' => '0','pids' => '0','name' => '云南','cname' => 'yunnan','child' => '0','hidden' => '0','childids' => '26','displayorder' => '0'),
    array('id' => '27','site' => '1','pid' => '0','pids' => '0','name' => '海南','cname' => 'hainan','child' => '0','hidden' => '0','childids' => '27','displayorder' => '0'),
    array('id' => '28','site' => '1','pid' => '0','pids' => '0','name' => '内蒙古','cname' => 'neimenggu','child' => '0','hidden' => '0','childids' => '28','displayorder' => '0'),
    array('id' => '29','site' => '1','pid' => '0','pids' => '0','name' => '新疆','cname' => 'xinjiang','child' => '0','hidden' => '0','childids' => '29','displayorder' => '0'),
    array('id' => '30','site' => '1','pid' => '0','pids' => '0','name' => '宁夏','cname' => 'ningxia','child' => '0','hidden' => '0','childids' => '30','displayorder' => '0'),
    array('id' => '31','site' => '1','pid' => '0','pids' => '0','name' => '西藏','cname' => 'xicang','child' => '0','hidden' => '0','childids' => '31','displayorder' => '0'),
    array('id' => '32','site' => '1','pid' => '0','pids' => '0','name' => '香港','cname' => 'xianggang','child' => '0','hidden' => '0','childids' => '32','displayorder' => '0'),
    array('id' => '33','site' => '1','pid' => '0','pids' => '0','name' => '澳门','cname' => 'aomen','child' => '0','hidden' => '0','childids' => '33','displayorder' => '0'),
    array('id' => '34','site' => '1','pid' => '0','pids' => '0','name' => '台湾','cname' => 'taiwan','child' => '0','hidden' => '0','childids' => '34','displayorder' => '0')
);